<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Tailor.Planning\Tailor.Planning.csproj" />
    <ProjectReference Include="..\Tailor.Validation\Tailor.Validation.csproj" />
    <ProjectReference Include="..\Tailor.Platform.Abstractions\Tailor.Platform.Abstractions.csproj" />
  </ItemGroup>

</Project>
